#!/usr/bin/env bash

# Update package list and install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Allow HTTP traffic through UFW
sudo ufw allow 'Nginx HTTP'

# Create index.html with "Hello World"
echo "Hello World" | sudo tee /var/www/html/index.html

# Create a new Nginx configuration file for redirection
sudo bash -c 'cat <<EOL > /etc/nginx/sites-available/my_redirect
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    location /redirect_me {
        rewrite ^/redirect_me https://www.youtube.com/ permanent;
    }
}
EOL'

# Create a symbolic link to enable the configuration
sudo ln -s /etc/nginx/sites-available/my_redirect /etc/nginx/sites-enabled/

# Restart Nginx to apply the configuration changes
sudo service nginx restart
