#!/usr/bin/env bash
# Double the number of webservers
sudo apt update
sudo apt install haproxy -y
# Backup the original haproxy.cfg file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
# Add configuration for web-01 and web-02
cat <<EOL | sudo tee -a /etc/haproxy/haproxy.cfg
listen myserver
    bind *:80
    balance roundrobin
    server web-01 34.203.201.4:80 check
    server web-02 34.207.253.176:80 check
EOL
sudo service haproxy restart
